### PR TITLE
Minimal modifications to allow running under python3

### PR DESCRIPTION
**Pull request by keskitalo**
Current master does not run under python3:
- module cPickle is named pickle in python3
- weave module is only available for legacy python2.X codes
- relative imports in __init__.py require reference points

This pull request addresses the above issues:
- when cPickle fails to load, fall back to pickle
- move the weave imports into the alternative "C" functions so only these flavors of the functions fail under python3.
- add "." relative directories into __init__.py

### CODE REVIEW

**Comment by keskitalo** [comment]
The relative imports seem to cause issues in the integration tests. I'll revise.

**Comment by keskitalo** [comment]
Problems fixed. Seems good to go.

**Comment by JulienPeloton** [comment]
Many thanks for testing and updating this! I reckon I just applied minimal modifications from 2 to 3, but I never really tested myself.

**Comment by JulienPeloton** [comment]
On aside, I will also test python3 in Travis to have automatic checks.

**Comment by JulienPeloton** [comment]
Just for your information, I have updated the travis script with python 3.5 and 3.6 (so it will automatically checks the code with those versions after each push), and remove all parts of the code using weave (it was not used anyway - I completely switched to fortran and f2py long ago). see https://github.com/JulienPeloton/s4cmb/pull/10 for the changes.

**Pull request merged**
