### PR TITLE
Updated flat sky visualization

### PR DESCRIPTION
**Pull request by markm42**
Updates made in the visualize_my_scan function:
1. The function now returns the hits map.
2. The flat sky visualisation projects the full sky hits map onto a square array considering the input resolution. Number of pixels in the awway will depend on resolution.

### CODE REVIEW

**Comment by JulienPeloton** [comment]
Thanks Mark for proposing changes! It's great to have flat-sky projection properly handled. 

I would suggest some modifications before merging though. The variable `fullsky` does not oppose flat vs curve sky, but actually cut vs full sky :-) So I would propose that you just re-arange the current structure to take into account both:

```python
# add a new arg to the routine called flatsky
def visualize_my_scan(..., fullsky=False, flatsky=False)

  # Compute nhits
  ...

  # Visualisation
  if fullsky:
    # mollview (that hasn't changed)
  else:
    if flatsky:
      # CartesianProj (keep what you inserted)
    else:
      # gnomview (bring back what you deleted)

  ...
```

What do you think?

**Comment by markm42** [comment]
Sorry, my mistake!
I added the flatsky variable now, and split the options between full+flat (the new projection), full+curved (mollview), or cut+curved (gnomview).
The currently missing option is cut+flat; technically one could create the full+flat and then crop the image as they please, but I could also work on that implementation if you think this would be useful to add?

**Comment by JulienPeloton** [comment]
Great thanks! Yes, having cut+flat would be perfect if you can :-)

**Comment by markm42** [comment]
Sorry it took so long - There are now 4 options for all combinations of curvature and sky area. When flatsky is True, the returned nhits is a square numpy array, otherwise it is a 1D healpy array. Let me know if further changes are required.

**Comment by JulienPeloton** [comment]
Thanks @markm42 for the modifications! Sorry it took so long to answer.

**Pull request merged**
